export type StudyLocation = {
  id: string;
  name: string;
  building: string;
  floor: string;
  description: string;
  amenities: string[];
  /** Typical capacity for occupancy ratio simulation */
  typicalCapacity: number;
  /** Base noise 0–100 (quieter = lower) */
  baselineNoise: number;
  /** Base busyness 0–100 */
  baselineBusyness: number;
};

/** Curated campus spots (merged with user-added entries from `data/custom-locations.json`) */
export const studyLocations: StudyLocation[] = [
  {
    id: "alexander-north-2",
    name: "Alexander Hall — North reading area",
    building: "Alexander Hall",
    floor: "2",
    description:
      "Open seating near windows; popular between classes. Good for solo reading.",
    amenities: ["Wi‑Fi", "Outlets", "Natural light"],
    typicalCapacity: 40,
    baselineNoise: 38,
    baselineBusyness: 62,
  },
  {
    id: "h-t-sam-lobby",
    name: "H.T. Sampson Library — Main floor",
    building: "H.T. Sampson Library",
    floor: "1",
    description:
      "Central hub with group tables and quiet zones. Check signage for silent study.",
    amenities: ["Wi‑Fi", "Printing", "Group tables", "Restrooms nearby"],
    typicalCapacity: 120,
    baselineNoise: 45,
    baselineBusyness: 78,
  },
  {
    id: "library-2-collab",
    name: "H.T. Sampson Library — 2nd floor collaborative zone",
    building: "H.T. Sampson Library",
    floor: "2",
    description: "Tables for partner work; expect moderate conversation.",
    amenities: ["Wi‑Fi", "Whiteboards", "Outlets"],
    typicalCapacity: 50,
    baselineNoise: 48,
    baselineBusyness: 65,
  },
  {
    id: "library-3-quiet",
    name: "H.T. Sampson Library — Quiet study (3rd floor)",
    building: "H.T. Sampson Library",
    floor: "3",
    description: "Designated low-conversation floor. Best for exams and deep work.",
    amenities: ["Wi‑Fi", "Carrels", "Outlets"],
    typicalCapacity: 55,
    baselineNoise: 22,
    baselineBusyness: 48,
  },
  {
    id: "student-center-lounge",
    name: "Student Center — Commuter lounge",
    building: "Jacob Reddix Campus Union",
    floor: "1",
    description: "Comfortable seating; more ambient noise. Better for light review.",
    amenities: ["Wi‑Fi", "Vending", "Microwaves nearby"],
    typicalCapacity: 65,
    baselineNoise: 58,
    baselineBusyness: 71,
  },
  {
    id: "union-food-court",
    name: "Campus Union — Food court seating",
    building: "Jacob Reddix Campus Union",
    floor: "1",
    description: "High foot traffic and mealtime noise; OK for quick tasks between classes.",
    amenities: ["Wi‑Fi", "Dining nearby"],
    typicalCapacity: 80,
    baselineNoise: 68,
    baselineBusyness: 82,
  },
  {
    id: "science-atrium",
    name: "Science & Engineering — Atrium benches",
    building: "Science & Engineering Complex",
    floor: "1",
    description: "Bright atrium with foot traffic; short sessions work well.",
    amenities: ["Wi‑Fi", "Whiteboards nearby"],
    typicalCapacity: 30,
    baselineNoise: 52,
    baselineBusyness: 55,
  },
  {
    id: "peoples-sci-2",
    name: "John A. Peoples Science Building — 2nd floor corridor niches",
    building: "John A. Peoples Science Building",
    floor: "2",
    description: "Bench seating between labs; variable noise when classes change.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 25,
    baselineNoise: 44,
    baselineBusyness: 58,
  },
  {
    id: "robinson-lobby",
    name: "Dollye M.E. Robinson Building — Main lobby",
    building: "Dollye M.E. Robinson Building",
    floor: "1",
    description: "Open lobby with mixed traffic; use for short focus blocks or group check-ins.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 45,
    baselineNoise: 50,
    baselineBusyness: 64,
  },
  {
    id: "moore-atrium",
    name: "Charles F. Moore Building — Atrium seating",
    building: "Charles F. Moore Building",
    floor: "1",
    description: "Central seating ring; echoes a bit when crowded.",
    amenities: ["Wi‑Fi", "Natural light"],
    typicalCapacity: 35,
    baselineNoise: 46,
    baselineBusyness: 59,
  },
  {
    id: "business-lounge",
    name: "College of Business — Student lounge",
    building: "College of Business",
    floor: "1",
    description: "Casual seating near advising; moderate noise during peak hours.",
    amenities: ["Wi‑Fi", "Outlets", "Screens nearby"],
    typicalCapacity: 40,
    baselineNoise: 47,
    baselineBusyness: 61,
  },
  {
    id: "education-commons",
    name: "College of Education & Human Development — Commons seating",
    building: "College of Education & Human Development",
    floor: "1",
    description: "Hallway clusters and soft seating; quieter in evenings.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 35,
    baselineNoise: 41,
    baselineBusyness: 52,
  },
  {
    id: "itc-stem-lobby",
    name: "Industrial Technology / STEM — Ground floor lobby",
    building: "Industrial Technology Center",
    floor: "1",
    description: "Transit-heavy but workable for quick reviews between labs.",
    amenities: ["Wi‑Fi", "High ceilings"],
    typicalCapacity: 28,
    baselineNoise: 49,
    baselineBusyness: 56,
  },
  {
    id: "miller-music-lobby",
    name: "L.T. Miller Hall (Music) — Lobby",
    building: "L.T. Miller Hall",
    floor: "1",
    description: "Can pick up rehearsal noise; good for casual reading when schedule is light.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 20,
    baselineNoise: 55,
    baselineBusyness: 45,
  },
  {
    id: "mccrary-honors",
    name: "B.F. McCrary Hall — Honors / shared study tables",
    building: "B.F. McCrary Hall",
    floor: "2",
    description: "Smaller footprint; tends to be calmer than the main library floor.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 28,
    baselineNoise: 35,
    baselineBusyness: 42,
  },
  {
    id: "residence-tiger-den",
    name: "Residence hall — Tiger study lounge (typical)",
    building: "Campus housing (varies)",
    floor: "Varies",
    description: "Use your building’s designated lounge; noise varies by night and events.",
    amenities: ["Wi‑Fi", "Kitchen nearby"],
    typicalCapacity: 24,
    baselineNoise: 42,
    baselineBusyness: 50,
  },
];
