export type StudyLocation = {
  id: string;
  name: string;
  building: string;
  floor: string;
  description: string;
  amenities: string[];
  /** Typical capacity for occupancy ratio simulation */
  typicalCapacity: number;
  /** Base noise 0–100 (quieter = lower) */
  baselineNoise: number;
  /** Base busyness 0–100 */
  baselineBusyness: number;
};

/**
 * Study spots aligned with the official JSU campus map / directory
 * (see https://www.jsums.edu/campusmap and https://www.jsums.edu/jsu-campus-directory).
 * Merged with user-added entries from `data/custom-locations.json`.
 */
export const studyLocations: StudyLocation[] = [
  {
    id: "sampson-library-1",
    name: "H.T. Sampson Library — Main floor",
    building: "H.T. Sampson Library",
    floor: "1",
    description:
      "Central services, group tables, and mixed quiet zones—check floor signage for silent study.",
    amenities: ["Wi‑Fi", "Printing", "Group tables", "Restrooms nearby"],
    typicalCapacity: 120,
    baselineNoise: 46,
    baselineBusyness: 78,
  },
  {
    id: "sampson-library-2",
    name: "H.T. Sampson Library — Second floor",
    building: "H.T. Sampson Library",
    floor: "2",
    description: "Collaborative tables and partner work; expect moderate conversation.",
    amenities: ["Wi‑Fi", "Whiteboards", "Outlets"],
    typicalCapacity: 55,
    baselineNoise: 48,
    baselineBusyness: 66,
  },
  {
    id: "sampson-library-quiet",
    name: "H.T. Sampson Library — Upper quiet floors",
    building: "H.T. Sampson Library",
    floor: "3+",
    description: "Designated low-conversation areas for exams and deep work.",
    amenities: ["Wi‑Fi", "Carrels", "Outlets"],
    typicalCapacity: 50,
    baselineNoise: 24,
    baselineBusyness: 48,
  },
  {
    id: "peoples-science",
    name: "John A. Peoples Science Building — Study niches & corridors",
    building: "John A. Peoples Science Building",
    floor: "Varies",
    description: "Bench seating and landings between labs; busier at class change.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 35,
    baselineNoise: 44,
    baselineBusyness: 58,
  },
  {
    id: "ee-just-hall",
    name: "Just Hall of Science — Commons & hallways",
    building: "Just Hall of Science",
    floor: "1–2",
    description: "Science quad traffic; good for short sessions and group touchpoints.",
    amenities: ["Wi‑Fi", "Lab corridors nearby"],
    typicalCapacity: 40,
    baselineNoise: 42,
    baselineBusyness: 55,
  },
  {
    id: "robinson-building",
    name: "Dollye M.E. Robinson Building — Lobby & atrium seating",
    building: "Dollye M.E. Robinson Building",
    floor: "1",
    description: "High visibility lobby; noise rises between classes.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 45,
    baselineNoise: 50,
    baselineBusyness: 64,
  },
  {
    id: "jackson-education",
    name: "Joseph H. Jackson Building (School of Education) — Student areas",
    building: "Joseph H. Jackson Building (School of Education)",
    floor: "Varies",
    description: "Hall seating and department commons; calmer evenings.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 35,
    baselineNoise: 40,
    baselineBusyness: 52,
  },
  {
    id: "college-of-business",
    name: "College of Business — Lounge & open study",
    building: "College of Business",
    floor: "Varies",
    description: "Near advising and classrooms; moderate bustle mid-day.",
    amenities: ["Wi‑Fi", "Outlets", "Screens nearby"],
    typicalCapacity: 40,
    baselineNoise: 46,
    baselineBusyness: 60,
  },
  {
    id: "school-of-engineering",
    name: "School of Engineering — Lobby & collaboration zones",
    building: "School of Engineering",
    floor: "1",
    description: "Project teams and foot traffic; better for active study blocks.",
    amenities: ["Wi‑Fi", "Whiteboards nearby"],
    typicalCapacity: 38,
    baselineNoise: 48,
    baselineBusyness: 57,
  },
  {
    id: "cset",
    name: "CSET — Building commons",
    building: "CSET",
    floor: "Varies",
    description: "Computing / STEM traffic; pair with headphones for focus.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 32,
    baselineNoise: 45,
    baselineBusyness: 54,
  },
  {
    id: "student-center-welcome",
    name: "JSU Student Center / Welcome Center — Main lounge",
    building: "JSU Student Center/Welcome Center",
    floor: "1",
    description: "Central student hub—comfortable but lively; great for breaks between tasks.",
    amenities: ["Wi‑Fi", "Vending", "Event boards"],
    typicalCapacity: 70,
    baselineNoise: 58,
    baselineBusyness: 74,
  },
  {
    id: "heritage-dining",
    name: "Heritage Dining Hall — Nearby seating & lobby",
    building: "Heritage Dining Hall",
    floor: "1",
    description: "Meal rush noise; quieter off-peak for light reading.",
    amenities: ["Wi‑Fi", "Dining"],
    typicalCapacity: 55,
    baselineNoise: 62,
    baselineBusyness: 80,
  },
  {
    id: "fd-hall-music",
    name: "F.D. Hall Center of Music — Lobby",
    building: "F.D. Hall Center of Music",
    floor: "1",
    description: "Possible rehearsal bleed-through; best when practice schedule is light.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 22,
    baselineNoise: 54,
    baselineBusyness: 46,
  },
  {
    id: "blackburn-language-arts",
    name: "W.D. Blackburn Language Arts — Hall study",
    building: "W.D. Blackburn Language Arts",
    floor: "Varies",
    description: "Humanities traffic; window benches on some floors.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 30,
    baselineNoise: 39,
    baselineBusyness: 50,
  },
  {
    id: "bf-roberts-hall",
    name: "B.F. Roberts Hall — Public seating",
    building: "B.F. Roberts Hall",
    floor: "Varies",
    description: "Class change spikes; steady mid-morning and late afternoon.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 28,
    baselineNoise: 41,
    baselineBusyness: 53,
  },
  {
    id: "ayer-hall",
    name: "Ayer Hall — Lobby & corridors",
    building: "Ayer Hall",
    floor: "1",
    description: "Historic core foot traffic; shorter focus sessions work well.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 25,
    baselineNoise: 43,
    baselineBusyness: 51,
  },
  {
    id: "jy-woodard",
    name: "J.Y. Woodard Building — Study spots",
    building: "J.Y. Woodard Building",
    floor: "Varies",
    description: "Departmental mix; quieter pockets on upper floors.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 28,
    baselineNoise: 40,
    baselineBusyness: 49,
  },
  
  {
    id: "cofo-building",
    name: "COFO Building — Public areas (when open)",
    building: "Council of Federated Organizations (COFO) Building",
    floor: "Varies",
    description: "Civil rights heritage site—respect posted hours and events.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 20,
    baselineNoise: 36,
    baselineBusyness: 38,
  },
  {
    id: "jl-reddix",
    name: "J.L. Reddix Building — Lobby seating",
    building: "J.L. Reddix Building",
    floor: "1",
    description: "Transit connector feel; OK for quick reviews.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 26,
    baselineNoise: 44,
    baselineBusyness: 56,
  },
  {
    id: "jones-sampson-hall",
    name: "Jones-Sampson Hall — Hall seating",
    building: "Jones-Sampson Hall",
    floor: "Varies",
    description: "Smaller footprint; variable by department activity.",
    amenities: ["Wi‑Fi", "Outlets"],
    typicalCapacity: 22,
    baselineNoise: 38,
    baselineBusyness: 45,
  },
  {
    id: "rose-mccoy-auditorium",
    name: "Rose E. McCoy Auditorium — Exterior plaza & lobby (events)",
    building: "Rose E. McCoy Auditorium",
    floor: "1",
    description: "Avoid during performances; plaza seating when clear.",
    amenities: ["Wi‑Fi", "Outdoor adjacent"],
    typicalCapacity: 35,
    baselineNoise: 48,
    baselineBusyness: 62,
  },
  {
    id: "international-programs",
    name: "International Programs — Visitor/student seating",
    building: "International Programs",
    floor: "Varies",
    description: "Lower volume than the main student center; confirm office hours.",
    amenities: ["Wi‑Fi", "Seating"],
    typicalCapacity: 18,
    baselineNoise: 34,
    baselineBusyness: 36,
  },
  {
    id: "alexander-residence",
    name: "Alexander Residence Hall — Hall study lounge",
    building: "Alexander Residence Hall",
    floor: "Varies",
    description: "Residents first; noise varies at night and on weekends.",
    amenities: ["Wi‑Fi", "Kitchen nearby"],
    typicalCapacity: 28,
    baselineNoise: 42,
    baselineBusyness: 50,
  },
  {
    id: "dixon-residence",
    name: "John W. Dixon Residence Hall — Study lounge",
    building: "John W. Dixon Residence Hall",
    floor: "Varies",
    description: "Typical residence lounge energy; earphones help.",
    amenities: ["Wi‑Fi", "Lounge furniture"],
    typicalCapacity: 24,
    baselineNoise: 44,
    baselineBusyness: 48,
  },
  {
    id: "stewart-residence",
    name: "E.T. Stewart Residence Hall — Study lounge",
    building: "E.T. Stewart Residence Hall",
    floor: "Varies",
    description: "Same patterns as other halls—quieter during class blocks.",
    amenities: ["Wi‑Fi", "Lounge furniture"],
    typicalCapacity: 24,
    baselineNoise: 43,
    baselineBusyness: 47,
  },
  {
    id: "campbell-suites",
    name: "Campbell College Residence Suites — Shared study space",
    building: "Campbell College Residence Suites (North & South)",
    floor: "Varies",
    description: "Suite-style community; use building-designated study zones.",
    amenities: ["Wi‑Fi", "Common areas"],
    typicalCapacity: 30,
    baselineNoise: 40,
    baselineBusyness: 49,
  },
  {
    id: "plant-science-garden",
    name: "Plant Science Building / Garden House — Nearby outdoor benches",
    building: "Plant Science Building / Garden House",
    floor: "Ground",
    description: "Weather-dependent; peaceful for reading when labs are quiet.",
    amenities: ["Wi‑Fi nearby", "Outdoor seating"],
    typicalCapacity: 16,
    baselineNoise: 28,
    baselineBusyness: 32,
  },
  {
    id: "jsu-downtown-capital",
    name: "JSU Downtown / 101 Capitol Centre — Public study (satellite)",
    building: "JSU Downtown / 101 Capitol Centre",
    floor: "Varies",
    description: "Downtown site for graduate and professional programs—confirm building access.",
    amenities: ["Wi‑Fi", "Urban setting"],
    typicalCapacity: 35,
    baselineNoise: 45,
    baselineBusyness: 52,
  },
];
